name: unity-meta-check
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  meta-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v7
        with:
          submodules: false
          lfs: true
      - name: Unity meta files check (github-hosted ubuntu-latest)
        uses: DeNA/unity-meta-check@v4
